### ISSUE TITLE
Display build version in Swagger UI

### ISSUE THREAD

**Issue by jbrelsf2-nmdp** [nmdp-bioinformatics/service-haplotype-frequency-curation#100]
Display the build version of the Phycus application in UI of phycus.b12x.org

**Comment by kaeaton** [comment]
A few questions:

1. Is this the build version of the GUI or the whole program, and where should I get the version number?
2. Where would you like me to list the version number? In options? Or as a footer on the upload page? Or another idea I haven't thought of?

**Comment by fscheel** [comment]
If I read this correctly, this issue concerns the swagger-ui and can be show here:
![image](https://user-images.githubusercontent.com/17205590/60647837-ea71d380-9e3e-11e9-8f8f-fbb78d7c569c.png)
