### ISSUE TITLE
Create Cohort API in the same pattern of Population API

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/service-haplotype-frequency-curation#63]
Create a Cohort API in the same pattern as the Population API except the POST for cohort requires a one (and only one) population ID.
![image](https://user-images.githubusercontent.com/8644904/37601844-0e34e78a-2b59-11e8-9bd9-724dfd5a138a.png)

GET cohort/
POST cohort/ (name and population ID are required)
GET cohort/{cohort ID}

**Comment by mpresteg** [comment]
Ultimately closed with pull request #67 .
