### ISSUE TITLE
Remove "CohortData" from HFCurationRequest and make CohortID(integer) required

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/service-haplotype-frequency-curation#65]
HFCurationRequest {
AccessData (AccessData, optional),
AccessID (integer, optional): References a access controls ,
CohortData (CohortData, optional),
CohortID (integer, optional): Cohort ID or genotype list ,
...

change to 
HFCurationRequest {
AccessData (AccessData, optional),
AccessID (integer, optional): References a access controls ,
CohortID (integer): Cohort ID or genotype list ,
...

**Comment by mpresteg** [comment]
Ultimately closed with pull request #67 .
